    This is the tutorial to Predict the flower based on the KNearest Algorithm
    Note: This is based on the sample data

    First Getting the Sample Data loaded and printing meta data

In [1]:
import pdb
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))
print("Targets:",iris_dataset['target_names'])
print("Features:",iris_dataset['feature_names'])


Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
Targets: ['setosa' 'versicolor' 'virginica']
Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


    Check the Data Structure

In [2]:
print("Type of data: {}".format(type(iris_dataset['data'])))
print("Shape of data: {}".format(iris_dataset['data'].shape))
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))
print("Type of target: {}".format(type(iris_dataset['target'])))
print("Shape of target: {}".format(iris_dataset['target'].shape))
print("Target:\n{}".format(iris_dataset['target']))

Type of data: <class 'numpy.ndarray'>
Shape of data: (150, 4)
First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Type of target: <class 'numpy.ndarray'>
Shape of target: (150,)
Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


    Splitting the data

In [3]:
from sklearn.model_selection import train_test_split
Train_Data, Test_Data, Train_Target, Test_Target = train_test_split(
iris_dataset['data'], iris_dataset['target'], random_state=0)
print("Train Data",Train_Data.shape)
print("Train Target", Train_Target.shape)
print("Test_Data", Test_Data.shape)
print("Test_Target", Test_Target.shape)

Train Data (112, 4)
Train Target (112,)
Test_Data (38, 4)
Test_Target (38,)


    Train Data And Target are matching so no data inconsitency here.
    Now lets do Scatter Plotter with pair plot
   

In [4]:
import pandas as pd 

iris_dataframe = pd.DataFrame(Test_Data, columns=iris_dataset.feature_names)
grr = pd.plotting.scatter_matrix(iris_dataframe, c=Test_Target, figsize=(15, 15), marker='o',
hist_kwds={'bins': 20}, s=60, alpha=.8)

    Using the K nearest Neighbour Algo
   

In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(Train_Data, Train_Target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

    Tesing the new data based on K nearest algo

In [6]:
import numpy as np
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
iris_dataset['target_names'][prediction]))
X_new_One = np.array([[15,0.6, 0.8, 0.2]])
prediction = knn.predict(X_new_One)
print("New Prediction: {}".format(
iris_dataset['target_names'][prediction]))

X_new.shape: (1, 4)
Prediction: [0]
Predicted target name: ['setosa']
New Prediction: ['versicolor']


     Lets Evaluate our model

In [7]:
prediction = knn.predict(Test_Data)
print("Test set predictions:\n {}".format(prediction))
print("Test set score: {:.2f}".format(np.mean(Test_Target == prediction)))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
Test set score: 0.97


       So it is 97% Accurate Prediction

    Let's change the algo to Random Forest
   

In [8]:
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(Train_Data, Train_Target);

    Lets try to predict earlier one

In [9]:
predictions = rf.predict(X_new)
print("Prediction: {}".format(predictions))
predictions = rf.predict(X_new_One)
print("Prediction: {}".format(predictions))



Prediction: [0.]
Prediction: [0.001]


    Find how it goes

In [10]:
prediction = rf.predict(Test_Data)
print("Test set predictions:\n {}".format(prediction))
print("Test set score: {:.2f}".format(np.mean(Test_Target == prediction)))

Test set predictions:
 [1.996e+00 1.015e+00 1.000e-03 1.998e+00 0.000e+00 2.000e+00 0.000e+00
 1.005e+00 1.063e+00 1.000e+00 1.854e+00 1.004e+00 1.002e+00 1.011e+00
 1.002e+00 0.000e+00 1.016e+00 1.000e+00 0.000e+00 0.000e+00 1.821e+00
 1.016e+00 0.000e+00 0.000e+00 1.812e+00 0.000e+00 0.000e+00 1.000e+00
 1.037e+00 0.000e+00 1.999e+00 1.020e+00 0.000e+00 1.818e+00 2.000e+00
 1.016e+00 1.000e-03 1.869e+00]
Test set score: 0.42


    So it is 42% Accurate
    Lets visualize the tree

In [17]:
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[15]
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[15]
# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names =iris_dataset['feature_names'], rounded = True, precision = 1)
# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
graph.write_png('tree.png')