    This is the tutorial to Predict the flower based on the KNearest Algorithm
    Note: This is based on the sample data

    First Getting the Sample Data loaded and printing meta data

In [9]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))
print("Targets:",iris_dataset['target_names'])
print("Features:",iris_dataset['feature_names'])


Keys of iris_dataset: 
['target_names', 'data', 'target', 'DESCR', 'feature_names']
('Targets:', array(['setosa', 'versicolor', 'virginica'], dtype='|S10'))
('Features:', ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'])


    Check the Data Structure

In [11]:
print("Type of data: {}".format(type(iris_dataset['data'])))
print("Shape of data: {}".format(iris_dataset['data'].shape))
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))
print("Type of target: {}".format(type(iris_dataset['target'])))
print("Shape of target: {}".format(iris_dataset['target'].shape))
print("Target:\n{}".format(iris_dataset['target']))

Type of data: <type 'numpy.ndarray'>
Shape of data: (150, 4)
First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Type of target: <type 'numpy.ndarray'>
Shape of target: (150,)
Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


    Splitting the data

In [15]:
from sklearn.model_selection import train_test_split
Train_Data, Test_Data, Train_Target, Test_Target = train_test_split(
iris_dataset['data'], iris_dataset['target'], random_state=0)
print("Train Data",Train_Data.shape)
print("Train Target", Train_Target.shape)
print("Test_Data", Test_Data.shape)
print("Test_Target", Test_Target.shape)

('Train Data', (112, 4))
('Train Target', (112,))
('Test_Data', (38, 4))
('Test_Target', (38,))


    Train Data And Target are matching so no data inconsitency here.
    Now lets do Scatter Plotter with pair plot
   

In [22]:
import pandas as pd 
import mglearn
iris_dataframe = pd.DataFrame(Test_Data, columns=iris_dataset.feature_names)
grr = pd.scatter_matrix(iris_dataframe, c=Test_Target, figsize=(15, 15), marker='o',
hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mglearn.cm3)

ImportError: No module named mglearn